### ISSUE TITLE
Is it possible to implement user access to sub directory level?

### ISSUE THREAD

**Issue by absjabed** [EvgenNoskov/Elfinder.NET#5]
**I am new working with elfinder- ASP.NET MVC. I am having some complex issues to implement a feature like where a user will create a New Folder (ex. Style Xyz) with 3 inner folder for example named 'COST', 'MIN', 'MAX' (already done!). 

Now I want to give the creator full access in 'COST' folder and read access to 'MIN' & 'MAX' folder. 
And there will be another 2 types of user groups one group will get full access to 'MIN' folder and another group will get full access to 'MAX' folder.

_I have already implemented 3 automatic sub folder creation within a new folder so i just want to know if it's possible to implement such complex ( to me :3 ) user access feature. If it is can you give me some hints or reference please?_
**

**Comment by EvgenNoskov** [comment]
Yes, you can add such logic.
For example, you can create a Connector class in the every request and confgure Roots according to current user rights. Every Root has IsReadOnly/IsShowOnly properties and they can be configured according to user access.

**Comment by absjabed** [comment]
done, thanks.
