### ISSUE TITLE
Search feature is not working.

### ISSUE THREAD

**Issue by absjabed** [EvgenNoskov/Elfinder.NET#6]
While working i found that search feature is not working. would you please let me know how i can make the search feature work?

**Comment by EvgenNoskov** [comment]
Search feature was not implemented.
You can make it by follow corresponding wiki page https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#search .
Search command should be added to Connector class, the properly processed and then returned appropriate response in format mentioned in the above link.

**Comment by absjabed** [comment]
done.
